version: "3"
networks:
  streetmix:
    external: true
    name: nat

services:
  streetmix_node:
    container_name: streetmix_node
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/src/app"
      - "streetmix_node_modules:/usr/src/app/node_modules"
      - "streetmix_node_modules2:/usr/src/app/client/node_modules"
    ports:
      - "8000:8000"
      - "1234:1234"
    # command: sleep infinity
    command: npm run start
    networks:
      - streetmix

volumes:
  streetmix_node_modules:
  streetmix_node_modules2:
